apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "igaming-proxy.fullname" . }}
  labels:
    {{- include "igaming-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "igaming-proxy.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "igaming-proxy.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              {{- include "igaming-proxy.selectorLabels" . | nindent 14 }}
      containers:
        - name: gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "igaming-proxy.fullname" . }}-secret
                  key: jwt-secret
                  optional: true
            - name: GEOIP_DB_PATH
              value: {{ .Values.config.geoipDbPath }}
            - name: CONFIG_DIR
              value: {{ .Values.config.configDir }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: geoip-data
              mountPath: /data
              readOnly: true
            - name: config
              mountPath: /app/configs
              readOnly: true
      volumes:
        - name: geoip-data
          persistentVolumeClaim:
            claimName: {{ .Values.geoip.volume.claimName }}
        - name: config
          configMap:
            name: {{ include "igaming-proxy.fullname" . }}-config
